# Generated by Django 4.2.6 on 2023-10-22 18:51

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project_Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=20)),
                ('exit_direction', models.CharField(max_length=50)),
                ('attention_threshold', models.FloatField(null=True)),
                ('alert_threshold', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_name', models.CharField(max_length=45)),
                ('structure_location', models.CharField(max_length=45)),
                ('inspection_frequency', models.CharField(max_length=45)),
                ('as_built_document', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uav_model', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=15)),
                ('component_list', models.CharField(max_length=45)),
                ('manual', models.CharField(max_length=45)),
                ('purchase_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('registration', models.IntegerField(unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Visual_Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField()),
                ('inspection_type', models.CharField(max_length=10)),
                ('pre_checklist', models.TextField()),
                ('state', models.CharField(max_length=8)),
                ('images', models.BinaryField()),
                ('observations', models.TextField()),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visual_inspection_on_structure_set', to='nesa.structure')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visual_inspection_set', to='nesa.uav')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nesa.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=20, unique=True)),
                ('sensor_model', models.CharField(max_length=15)),
                ('latitude', models.FloatField(default=None)),
                ('longitude', models.FloatField(default=None)),
                ('altura', models.FloatField(default=None)),
                ('cluster', models.IntegerField(default=None)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensor_set', to='nesa.structure')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateTimeField()),
                ('measurement_unit', models.CharField(max_length=10)),
                ('exit_direction', models.CharField(max_length=50)),
                ('manual_report', models.TextField()),
                ('sensor_data', models.FloatField()),
                ('state', models.CharField(choices=[('normal', 'normal'), ('atencao', 'atencao'), ('alerta', 'alerta'), ('emergencia', 'emergencia')], default='normal', max_length=10)),
                ('project_attention_threshold', models.FloatField(null=True)),
                ('project_alert_threshold', models.FloatField(null=True)),
                ('attention_threshold', models.FloatField(null=True)),
                ('alert_threshold', models.FloatField(null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_sensor_set', to='nesa.sensor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_user_set', to='nesa.user')),
            ],
        ),
        migrations.CreateModel(
            name='Machine_Learning_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('images', models.BinaryField()),
                ('results', models.TextField()),
                ('visual_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_set', to='nesa.visual_inspection')),
            ],
        ),
    ]
