# Generated by Django 4.2.6 on 2023-10-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_threshold',
            name='sensor_name',
        ),
        migrations.AddField(
            model_name='project_threshold',
            name='sensor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='threshold_sensor_set', to='nesa.sensor'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='project_threshold',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_threshold_set', to='nesa.project_threshold'),
        ),
    ]
