# Generated by Django 4.2.6 on 2023-10-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0002_remove_project_threshold_sensor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='project_threshold',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_threshold_set', to='nesa.project_threshold'),
        ),
    ]
