# Generated by Django 4.2.6 on 2023-10-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0003_alter_sensor_project_threshold'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project_threshold',
            unique_together={('sensor', 'exit_direction')},
        ),
    ]
