# Generated by Django 4.2.7 on 2023-12-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0004_alter_project_threshold_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('initial_date', models.DateTimeField()),
                ('final_date', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='models_sensor_set', to='nesa.sensor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='models_user_set', to='nesa.user')),
            ],
        ),
    ]
