# Generated by Django 4.2.7 on 2023-12-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0005_modelslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelslog',
            name='final_date',
        ),
        migrations.RemoveField(
            model_name='modelslog',
            name='initial_date',
        ),
        migrations.RemoveField(
            model_name='modelslog',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='modelslog',
            name='timestamp',
        ),
    ]
