# Generated by Django 4.2.7 on 2023-12-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0006_remove_modelslog_final_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelslog',
            name='sensor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='models_sensor_set', to='nesa.sensor'),
        ),
    ]
