# Generated by Django 4.2.7 on 2023-12-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0008_alter_modelslog_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelslog',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models_sensor_set', to='nesa.sensor'),
        ),
        migrations.AlterField(
            model_name='modelslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_user_set', to='nesa.user'),
        ),
    ]
