# Generated by Django 4.2.7 on 2023-12-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0011_alter_modelslog_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelslog',
            name='sensor',
        ),
    ]
