# Generated by Django 4.2.7 on 2023-12-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0012_remove_modelslog_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelslog',
            name='sensor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models_sensor_set', to='nesa.sensor'),
        ),
    ]
