# Generated by Django 4.2.7 on 2023-12-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0013_modelslog_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelslog',
            name='final_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='modelslog',
            name='initial_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='modelslog',
            name='timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
