# Generated by Django 4.2.7 on 2024-01-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0014_modelslog_final_date_modelslog_initial_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelslog',
            name='structure',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models_structure_set', to='nesa.structure'),
        ),
    ]
