# Generated by Django 4.2.7 on 2024-01-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0015_modelslog_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelslog',
            name='structure',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
    ]
