# Generated by Django 4.2.7 on 2024-01-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0017_remove_modelslog_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelslog',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nesa.structure'),
        ),
    ]
