# Generated by Django 4.2.7 on 2024-01-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0018_modelslog_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelslog',
            name='structure',
        ),
    ]
