# Generated by Django 4.2.7 on 2024-01-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0020_modelslog_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelslog',
            name='final_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='modelslog',
            name='initial_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
