# Generated by Django 4.2.7 on 2024-02-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0021_alter_modelslog_final_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visual_inspection',
            name='pre_checklist',
        ),
        migrations.RemoveField(
            model_name='visual_inspection',
            name='state',
        ),
        migrations.AddField(
            model_name='visual_inspection',
            name='inspector_in_charge',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='visual_inspection',
            name='images',
            field=models.FilePathField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='visual_inspection',
            name='inspection_type',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visual_inspection',
            name='uav',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
