# Generated by Django 4.2.7 on 2024-02-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0022_remove_visual_inspection_pre_checklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visual_inspection',
            name='images',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
