# Generated by Django 4.2.11 on 2024-05-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nesa", "0023_alter_visual_inspection_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoxPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("lower_whisker", models.FloatField()),
                ("lower_quartile", models.FloatField()),
                ("median", models.FloatField()),
                ("upper_quartile", models.FloatField()),
                ("upper_whisker", models.FloatField()),
                ("means", models.FloatField()),
                ("count1", models.FloatField()),
                ("count2", models.FloatField()),
                ("count3", models.FloatField()),
                ("count4", models.FloatField()),
                ("metric", models.FloatField()),
                ("bin1", models.IntegerField()),
                ("bin2", models.IntegerField()),
                ("bin3", models.IntegerField()),
                ("bin4", models.IntegerField()),
                ("bin5", models.IntegerField()),
                ("bin6", models.IntegerField()),
                ("bin7", models.IntegerField()),
                ("bin8", models.IntegerField()),
                ("bin9", models.IntegerField()),
                ("bin10", models.IntegerField()),
                ("bin11", models.IntegerField()),
                ("bin12", models.IntegerField()),
                ("bin13", models.IntegerField()),
                ("bin14", models.IntegerField()),
                ("bin15", models.IntegerField()),
                ("bin16", models.IntegerField()),
                ("bin17", models.IntegerField()),
                ("bin18", models.IntegerField()),
                ("bin19", models.IntegerField()),
                ("bin20", models.IntegerField()),
                (
                    "boxplot_inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxplot_inspection_set",
                        to="nesa.visual_inspection",
                    ),
                ),
                (
                    "boxplot_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxplot_structure_set",
                        to="nesa.structure",
                    ),
                ),
            ],
        ),
    ]
