# Generated by Django 4.2.11 on 2024-05-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0023_alter_visual_inspection_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('measurement', models.FloatField(null=True)),
                ('sensor', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('exit_direction', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
    ]
