# Generated by Django 4.2.11 on 2024-05-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nesa', '0024_boxplot'),
        ('nesa', '0024_waterlevels'),
    ]

    operations = [
    ]
